name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: npx vercel --prod -y
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
