name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: npx vercel --prod -y
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
